#!/bin/sh

die() {
    local code=$1
    shift
    echo $*
    exit $code
}


is_running() {
    cat $1 | python -c 'import sys,json;print("yes" if "executable" in json.load(sys.stdin) else "no")'
}


wait_for_start() {
    local out qurl
    out=$1
    qurl="`sed -n -E -e 's/^Location:(.*)[[:cntrl:]]+$/\1/p' $out`"
    qurl="`echo $qurl | sed 's/\\/$//'`"
    #echo 'out >>>'
    #cat $out
    #echo '<<<'
    while true
    do
        curl -q -s --user $user:$token ${qurl}/api/json >out.wfs
        isrunning=`is_running out.wfs`
        if test "$isrunning" = yes
        then
            break
        elif test "$isrunning" = no
        then
            continue
        else
            echo exception breaking out
            break
        fi
        sleep 2
    done
    rm -f out.wfs
}


mbnp=http://big-1:8180/jenkins/job/mndev-matrix/build
pbnp=http://big-1:8180/jenkins/job/mndev-pipeline/build
pbwp=http://big-1:8180/jenkins/job/mndev-pipeline/buildWithParameters
ppvc=http://big-1:8180/jenkins/pluginManager/prevalidateConfig
pinp=http://big-1:8180/jenkins/pluginManager/installNecessaryPlugins
pucp=http://big-1:8180/jenkins/updateCenter/site/default/plugin/.../api/json?depth=1

user=admin
token=11849bbac29f35af1e66fcc95b08c7923f

#set -x
if test "$1" = run-pipeline
then
    #envs="init"
    envs="init dev dev-ndebug"
    modules="mndiag mncommon mnl4c mnthr mnapp mnyaml mnspinfo mnprotobuf mnmath mnlipc"

    # XXX convert ot pipeline matrix
    for env in $envs
    do
        for mod in $modules
        do
            echo ======= $env $mod
            #form="{\"parameter\":[{\"name\":\"module\",\"value\":\"$mod\"},{\"name\":\"setupenv\",\"value\":\"$env\"}],\"delay\":10sec}"
            #curl -q -s --dump-header out --user $user:$token --data-urlencode "json=$form" ${pbnp}
            form="module=${mod}&setupenv=${env}"
            curl -q -s --dump-header out -X POST --user $user:$token "${pbwp}?${form}"
            wait_for_start out
        done
    done

    #module=mndiag
    #setupenv=init
    #form="{\"parameter\":[{\"module\":\"$module\"},{\"setupenv\":\"$setupenv\"}]}"
    #curl -v --dump-header out  --user $user:$token --data-urlencode "json=$form" $pbwp
    #wait_for_start out

elif test "$1" = run-matrix
then
    curl -q -s --dump-header out -X POST --user $user:$token "${mbnp}"
    wait_for_start out

elif test "$1" = validate
then
    fname=$2
    if test -f "$fname"
    then
        curl -v --user $user:$token --data @$fname $ppvc
    else
        die 1 "no such file: $fname"
    fi

elif test "$1" = install
then
    fname=$2
    if test -f "$fname"
    then
        curl -v --user $user:$token --data @$fname $pinp
    else
        die 1 "no such file: $fname"
    fi

else
    die 1 "invalid command: $1"
fi
