#!/bin/sh

_run() {
    echo "running $@ ..."
    eval "$@" >/dev/null 2>&1
}

die() {
    echo $*
    exit 1
}

do_init() {
    _run autoreconf --force
    if test $? -ne 0
    then
        if test -e .ac-aux/missing
        then
            die fix your errors
        fi
    fi
    _run aclocal
    _run autoheader
    _run autoreconf
    _run automake --add-missing
    _run libtoolize
    _run make distclean
    _run autoreconf
    ./configure
}

do_dev() {
    autoreconf --force
    ./configure
}


if test "$1" = "init"
then
    do_init

elif test "$1" = "dev"
then
    do_dev
fi
