---
-
    name: Development
    hosts: dev
    remote_user: "{{ ruser }}"
    gather_facts: true
    strategy: debug
    tasks:
        - import_role:
            name: development

        - name: git prepare mnbase from local
          tags:
              - gitup-local
              - mnbase
          git:
              repo: mkushnir@big-1:development/{{ item['name'] }}
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mnbase }}"

        - name: git prepare mnextra from local
          tags:
              - gitup-local
              - mnextra
          git:
              repo: mkushnir@big-1:development/{{ item['name'] }}
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mnextra }}"

        - name: git prepare mnproto from local
          tags:
              - gitup-local
              - mnproto
          git:
              repo: mkushnir@big-1:development/{{ item['name'] }}
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mnproto }}"

        - name: git prepare mndb from local
          tags:
              - gitup-local
              - mndb
          git:
              repo: mkushnir@big-1:development/{{ item['name'] }}
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mndb }}"

        - name: git prepare mntest from local
          tags:
              - gitup-local
              - mntest
          git:
              repo: mkushnir@big-1:development/{{ item['name'] }}
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mntest }}"

        - name: setup-env init mn(base|extra|proto)
          tags:
              - development-init
          shell: PATH=$HOME/bin:$PATH; cd $HOME/development/{{ item['name'] }} && ./setup-env init
          with_items: "{{ mnbase + mnextra + mnproto }}"


        - name: setup-env dev mn(base|extra|proto)
          tags:
              - development-dev
          shell: PATH=$HOME/bin:$PATH; cd $HOME/development/{{ item['name'] }} && ./setup-env {{ item.get('dev', 'dev') }}
          with_items: "{{ mnbase + mnextra + mnproto }}"


        - name: make clean mn(base|extra|proto)
          tags:
              - development-clean
          shell: PATH=$HOME/bin:$PATH; cd $HOME/development/{{ item['name'] }} && make clean
          with_items: "{{ mnbase + mnextra + mnproto }}"

        - name: make install mn(base|extra|proto)
          tags:
              - development-install
          shell: PATH=$HOME/bin:$PATH; cd $HOME/development/{{ item['name'] }} && make install
          with_items: "{{ mnbase + mnextra + mnproto }}"
          register: res
          changed_when: "' CC ' in res.stdout"

        #- name: DDD
        #  tags:
        #      - development-install
        #  debug:
        #      var: res

        - name: make uninstall mn(base|extra|proto)
          tags:
              - development-uninstall
          shell: PATH=$HOME/bin:$PATH; cd $HOME/development/{{ item['name'] }} && make uninstall
          with_items: "{{ mnbase + mnextra + mnproto }}"

        - name: purge installed
          tags:
              - development-clean
          #shell: rm -Rf $HOME/include/mn* $HOME/lib/libmn* $HOME/lib/mn*
          file:
              path: $HOME/include/mn* $HOME/lib/libmn*
              state: absent


        - name: git prepare mnbase from github.com
          tags: gitup-gh
          git:
              repo: mkushnir@github.com:{{ item['name'] }}.git
              dest: $HOME/development/{{ item['name'] }}
              accept_hostkey: yes
          with_items: "{{ mnbase }}"

        #- name: init project
        #  tags: mn-init

